@startuml SGA

  left to right direction
  skinparam packageStyle rectangle

  ' Definição de Atores
  actor Proprietário
  actor Convidado
  
  ' Definição do Sistema
  rectangle "Sistema de Análise de Documentos" {
      ' Casos de Uso no Sistema
      usecase "Autenticação" as AT 
      usecase "Autorização" as AU 
      usecase "Filiação" as FL
      usecase "Descritor" as DS
      usecase "projeto" as PJ
      usecase "Convite" as CV
      usecase "Correlação" as CR
  }

  ' Conexões
  Convidado -- AT 
  AT <|- AU
  Convidado -- FL
  Convidado -- PJ
  Convidado -- CV
  Convidado -- CR
  Convidado <|- Proprietário

@enduml

