@startuml MER

  ' Entidades e Atributos
  entity "Login" {
    * id_login : integer [PK, Auto Increment]
    --
    * email : varchar(40) [Unique]
    * senha : varchar(60)
    * nome : varchar(40)
  }

  entity "Filiação" {
    * id_perfil : integer [PK, Auto Increment]
    * id_login : integer [Unique, FK to Login.id_login]
    --
    nome : varchar(40)
    endereco : varchar(40)
    cidade : varchar(30)
    bairro : varchar(30)
    uf : varchar(2)
  }

  ' Relacionamentos
  Login "1" ||--O{ "N" Filiação

@enduml
